english_turkish_dict = {
    "be": ["olmak", "verb"],
    "and": ["ve", "conjunction"],
    "of": ["-ın", "-nın", "preposition"],
    "in": ["içinde", "içine", "preposition"],
    "to": ["-e", "-a", "preposition"],
    "have": ["sahip olmak", "verb"],
    "it": ["o", "onu", "pronoun"],
    "I": ["ben", "pronoun"],
    "that": ["şu", "o", "pronoun", "conjunction"],
    "for": ["için", "preposition"],
    "you": ["sen", "siz", "pronoun"],
    "he": ["o (erkek)", "pronoun"],
    "with": ["ile", "preposition"],
    "on": ["üzerinde", "üstünde", "preposition"],
    "do": ["yapmak", "verb"],
    "say": ["söylemek", "verb"],
    "this": ["bu", "pronoun"],
    "they": ["onlar", "pronoun"],
    "at": ["-de", "-da", "yanında", "preposition"],
    "but": ["fakat", "ama", "conjunction"],
    "we": ["biz", "pronoun"],
    "his": ["onun (erkek)", "possessive pronoun"],
    "from": ["-den", "-dan", "preposition"],
    "not": ["değil", "adverb"],
    "by": ["tarafından", "yanında", "preposition"],
    "she": ["o (kadın)", "pronoun"],
    "or": ["veya", "conjunction"],
    "as": ["gibi", "preposition"],
    "what": ["ne", "pronoun"],
    "go": ["gitmek", "verb"],
    "their": ["onların", "possessive pronoun"],
    "can": ["-e bilmek", "kutu", "verb", "noun"],
    "who": ["kim", "pronoun"],
    "get": ["almak", "elde etmek", "verb"],
    "if": ["eğer", "conjunction"],
    "would": ["-erdi", "-ardı", "modal verb"],
    "her": ["onun (kadın)", "ona", "possessive pronoun", "pronoun"],
    "all": ["hepsi", "adjective"],
    "my": ["benim", "possessive pronoun"],
    "make": ["yapmak", "verb"],
    "about": ["hakkında", "yaklaşık", "preposition", "adjective"],
    "know": ["bilmek", "verb"],
    "will": ["-ecek", "-acak", "modal verb"],
    "up": ["yukarı", "artmak", "adverb", "preposition"],
    "one": ["bir", "noun", "adjective"],
    "time": ["zaman", "noun"],
    "there": ["orada", "adverb"],
    "year": ["yıl", "noun"],
    "so": ["bu yüzden", "çok", "adverb", "conjunction"],
    "think": ["düşünmek", "verb"],
    "when": ["ne zaman", "conjunction"],
    "which": ["hangi", "pronoun"],
    "them": ["onları", "onlara", "pronoun"],
    "some": ["bazı", "birkaç", "pronoun", "adjective"],
    "me": ["beni", "bana", "pronoun"],
    "people": ["insanlar", "noun"],
    "take": ["almak", "verb"],
    "out": ["dışarı", "adverb"],
    "into": ["içine", "preposition"],
    "just": ["sadece", "tam", "adverb", "adjective"],
    "see": ["görmek", "verb"],
    "him": ["onu (erkek)", "pronoun"],
    "your": ["senin", "sizin", "possessive pronoun"],
    "come": ["gelmek", "verb"],
    "could": ["-ebilmek (geçmiş zaman)", "modal verb"],
    "now": ["şimdi", "adverb"],
    "than": ["-den", "-dan", "conjunction"],
    "like": ["sevmek", "gibi", "verb", "preposition"],
    "other": ["diğer", "başka", "adjective"],
    "how": ["nasıl", "adverb"],
    "then": ["sonra", "adverb"],
    "its": ["onun (cansız varlık)", "possessive pronoun"],
    "our": ["bizim", "possessive pronoun"],
    "two": ["iki", "noun"],
    "more": ["daha fazla", "adverb", "adjective"],
    "these": ["bunlar", "pronoun"],
    "want": ["istemek", "verb"],
    "way": ["yol", "yöntem", "noun"],
    "look": ["bakmak", "verb"],
    "first": ["ilk", "adjective"],
    "also": ["aynı zamanda", "de", "adverb"],
    "new": ["yeni", "adjective"],
    "because": ["çünkü", "conjunction"],
    "day": ["gün", "noun"],
    "use": ["kullanmak", "verb"],
    "no": ["hayır", "adverb"],
    "man": ["adam", "erkek", "noun"],
    "find": ["bulmak", "verb"],
    "here": ["burada", "adverb"],
    "thing": ["şey", "noun"],
    "give": ["vermek", "verb"],
    "many": ["birçok", "adjective"],
    "well": ["iyi", "adverb"],
    "only": ["sadece", "adverb", "adjective"],
    "those": ["şunlar", "pronoun"],
    "tell": ["söylemek", "verb"],
    "very": ["çok", "adverb"],
    "even": ["bile", "hatta", "adverb"],
    "back": ["geri", "adverb", "noun"],
    "any": ["herhangi", "adjective", "pronoun"],
    "good": ["iyi", "adjective"],
    "woman": ["kadın", "noun"],
    "through": ["içinden", "boyunca", "preposition"],
    "us": ["bizi", "bize", "pronoun"],
    "life": ["hayat", "yaşam", "noun"],
    "child": ["çocuk", "noun"],
    "work": ["çalışmak", "iş", "verb", "noun"],
    "down": ["aşağı", "düşürmek", "adverb", "preposition"],
    "may": ["-e bilmek", "mayıs", "modal verb", "noun"],
    "after": ["sonra", "preposition"],
    "should": ["-meli", "-malı", "modal verb"],
    "call": ["çağırmak", "aramak", "verb"],
    "world": ["dünya", "noun"],
    "over": ["üzerinde", "preposition"],
    "school": ["okul", "noun"],
    "still": ["hala", "adverb"],
    "try": ["denemek", "verb"],
    "last": ["son", "adjective"],
    "ask": ["sormak", "verb"],
    "need": ["ihtiyaç duymak", "verb"],
    "too": ["çok", "fazla", "adverb"],
    "feel": ["hissetmek", "verb"],
    "three": ["üç", "noun"],
    "state": ["durum", "eyalet", "noun"],
    "never": ["asla", "adverb"],
    "become": ["olmak", "haline gelmek", "verb"],
    "between": ["arasında", "preposition"],
    "high": ["yüksek", "adjective"],
    "really": ["gerçekten", "adverb"],
    "something": ["bir şey", "pronoun"],
    "most": ["en fazla", "adjective"],
    "another": ["başka bir", "adjective"],
    "much": ["çok", "adjective", "adverb"],
    "family": ["aile", "noun"],
    "own": ["kendi", "adjective"],
    "leave": ["ayrılmak", "terk etmek", "verb"],
    "put": ["koymak", "verb"],
    "old": ["eski", "yaşlı", "adjective"],
    "while": ["iken", "esnasında", "conjunction"],
    "mean": ["anlamına gelmek", "demek istemek", "verb"],
    "keep": ["tutmak", "korumak", "verb"],
    "student": ["öğrenci", "noun"],
    "why": ["neden", "adverb"],
    "let": ["izin vermek", "allow", "verb"],
    "great": ["harika", "büyük", "adjective"],
    "same": ["aynı", "adjective"],
    "another": ["başka bir", "adjective"],
    "start": ["başlamak", "verb"],
    "work": ["çalışmak", "iş", "verb", "noun"],
    "place": ["yer", "mekan", "noun"],
    "large": ["büyük", "adjective"],
    "own": ["kendi", "adjective"],
    "put": ["koymak", "verb"],
    "end": ["son", "bitiş", "noun"],
    "right": ["doğru", "sağ", "adjective", "noun"],
    "wrong": ["yanlış", "adjective"],
    "often": ["sık sık", "adverb"],
    "different": ["farklı", "adjective"],
    "whole": ["bütün", "adjective"],
    "public": ["kamu", "adjective"],
    "social": ["sosyal", "adjective"],
    "economy": ["ekonomi", "noun"],
    "history": ["tarih", "noun"],
    "well": ["iyi", "adverb"],
    "fact": ["gerçek", "noun"],
    "few": ["az", "adjective"],
    "number": ["sayı", "noun"],
    "around": ["etrafında", "adverb"],
    "help": ["yardım etmek", "verb"],
    "make": ["yapmak", "oluşturmak", "verb"],
    "try": ["denemek", "çabalamak", "verb"],
    "change": ["değiştirmek", "değişim", "verb", "noun"],
    "find": ["bulmak", "discover", "verb"],
    "real": ["gerçek", "adjective"],
    "possible": ["mümkün", "adjective"],
    "come": ["gelmek", "verb"],
    "small": ["küçük", "adjective"],
    "lead": ["öncülük etmek", "önderlik yapmak", "verb"],
    "control": ["kontrol etmek", "denetlemek", "verb"],
    "process": ["işlem", "süreç", "noun"],
    "clear": ["açık", "net", "adjective"],
    "understand": ["anlamak", "verb"],
    "provide": ["sağlamak", "verb"],
    "new": ["yeni", "adjective"],
    "plan": ["plan", "noun", "verb"],
    "support": ["desteklemek", "verb"],
    "create": ["yaratmak", "oluşturmak", "verb"],
    "complete": ["tamamlamak", "adjective"],
    "strategy": ["strateji", "noun"],
    "national": ["ulusal", "adjective"],
    "region": ["bölge", "noun"],
    "address": ["adres", "hitap etmek", "noun", "verb"],
    "question": ["soru", "noun"],
    "response": ["yanıt", "noun"],
    "type": ["tip", "tür", "noun", "verb"],
    "solution": ["çözüm", "noun"],
    "message": ["mesaj", "noun"],
    "service": ["hizmet", "noun"],
    "form": ["şekil", "form", "noun"],
    "course": ["kurs", "yön", "noun"],
    "article": ["makale", "noun"],
    "company": ["şirket", "noun"],
    "system": ["sistem", "noun"],
    "source": ["kaynak", "noun"],
    "factor": ["etken", "faktör", "noun"],
    "target": ["hedef", "noun"],
    "opinion": ["görüş", "opinion", "noun"],
    "case": ["durum", "vaka", "noun"],
    "result": ["sonuç", "noun"],
    "research": ["araştırma", "noun", "verb"],
    "policy": ["politika", "noun"],
    "experience": ["deneyim", "tecrübe", "noun"],
    "impact": ["etki", "noun"],
    "product": ["ürün", "noun"],
    "service": ["hizmet", "noun"],
    "success": ["başarı", "noun"],
    "change": ["değişim", "verb"],
    "issue": ["konu", "sorun", "noun"],
    "structure": ["yapı", "noun"],
    "role": ["rol", "noun"],
    "goal": ["hedef", "noun"],
    "approach": ["yaklaşım", "noun"],
    "challenge": ["meydan okuma", "noun"],
    "market": ["pazar", "noun"],
    "development": ["gelişim", "noun"],
    "team": ["takım", "noun"],
    "strategy": ["strateji", "noun"],
    "goal": ["hedef", "noun"],
    "method": ["yöntem", "noun"],
    "data": ["veri", "noun"],
    "factor": ["etken", "noun"],
    "goal": ["amaç", "noun"],
    "information": ["bilgi", "noun"],
    "event": ["etkinlik", "olay", "noun"],
    "support": ["destek", "noun"],
    "communication": ["iletişim", "noun"],
    "project": ["proje", "noun"],
    "plan": ["plan", "noun"],
    "analysis": ["analiz", "noun"],
    "resource": ["kaynak", "noun"],
    "decision": ["karar", "noun"],
    "process": ["süreç", "noun"],
    "method": ["yöntem", "noun"],
    "goal": ["hedef", "noun"],
    "assessment": ["değerlendirme", "noun"],
    "standard": ["standart", "noun"],
    "procedure": ["prosedür", "noun"],
    "quality": ["kalite", "noun"],
    "document": ["belge", "noun"],
    "plan": ["plan", "noun"],
    "review": ["gözden geçirme", "noun"],
    "result": ["sonuç", "noun"],
    "performance": ["performans", "noun"],
    "benefit": ["yarar", "noun"],
    "able": ["yetenekli", "adj"],
    "about": ["hakkında", "prep"],
    "above": ["üstünde", "prep"],
    "accept": ["kabul etmek", "verb"],
    "access": ["erişim", "noun"],
    "account": ["hesap", "noun"],
    "across": ["karşısında", "prep"],
    "act": ["hareket etmek", "verb"],
    "additional": ["ek", "adj"],
    "affect": ["etkilemek", "verb"],
    "after": ["sonra", "prep"],
    "against": ["karşı", "prep"],
    "almost": ["neredeyse", "adv"],
    "among": ["arasında", "prep"],
    "amount": ["miktar", "noun"],
    "analysis": ["analiz", "noun"],
    "any": ["herhangi", "adj"],
    "apply": ["başvurmak", "verb"],
    "area": ["alan", "noun"],
    "average": ["ortalama", "noun"],
    "back": ["geri", "noun"],
    "become": ["olmak", "verb"],
    "benefit": ["yarar", "noun"],
    "between": ["arasında", "prep"],
    "beyond": ["ötesinde", "prep"],
    "brought": ["getirdi", "verb"],
    "calculate": ["hesaplamak", "verb"],
    "change": ["değişiklik", "noun"],
    "common": ["yaygın", "adj"],
    "company": ["şirket", "noun"],
    "consider": ["düşünmek", "verb"],
    "continue": ["devam etmek", "verb"],
    "create": ["oluşturmak", "verb"],
    "current": ["şu anki", "adj"],
    "data": ["veri", "noun"],
    "define": ["tanımlamak", "verb"],
    "design": ["tasarım", "noun"],
    "develop": ["geliştirmek", "verb"],
    "difference": ["fark", "noun"],
    "discover": ["keşfetmek", "verb"],
    "discussion": ["tartışma", "noun"],
    "document": ["belge", "noun"],
    "due": ["vadesi gelmiş", "adj"],
    "effect": ["etki", "noun"],
    "either": ["ya da", "conj"],
    "element": ["öğe", "noun"],
    "employ": ["istihdam etmek", "verb"],
    "end": ["son", "noun"],
    "entire": ["tam", "adj"],
    "evaluate": ["değerlendirmek", "verb"],
    "evidence": ["delil", "noun"],
    "factor": ["etken", "noun"],
    "final": ["son", "adj"],
    "focus": ["odak", "noun"],
    "follow": ["takip etmek", "verb"],
    "form": ["şekil", "noun"],
    "future": ["gelecek", "noun"],
    "growth": ["büyüme", "noun"],
    "individual": ["birey", "noun"],
    "involve": ["dahil olmak", "verb"],
    "issue": ["konu", "noun"],
    "large": ["büyük", "adj"],
    "likely": ["muhtemel", "adj"],
    "major": ["büyük", "adj"],
    "method": ["yöntem", "noun"],
    "model": ["model", "noun"],
    "need": ["ihtiyaç", "noun"],
    "occur": ["meydana gelmek", "verb"],
    "opportunity": ["fırsat", "noun"],
    "option": ["seçenek", "noun"],
    "particular": ["belirli", "adj"],
    "pattern": ["desen", "noun"],
    "place": ["yer", "noun"],
    "possible": ["mümkün", "adj"],
    "present": ["sunmak", "verb"],
    "previous": ["önceki", "adj"],
    "provide": ["sağlamak", "verb"],
    "purpose": ["amaç", "noun"],
    "range": ["aralık", "noun"],
    "recent": ["son", "adj"],
    "region": ["bölge", "noun"],
    "require": ["gerektirmek", "verb"],
    "result": ["sonuç", "noun"],
    "review": ["gözden geçirme", "noun"],
    "role": ["rol", "noun"],
    "safety": ["güvenlik", "noun"],
    "search": ["arama", "verb"],
    "section": ["bölüm", "noun"],
    "service": ["hizmet", "noun"],
    "significant": ["önemli", "adj"],
    "similar": ["benzer", "adj"],
    "source": ["kaynak", "noun"],
    "specific": ["özel", "adj"],
    "structure": ["yapı", "noun"],
    "system": ["sistem", "noun"],
    "target": ["hedef", "noun"],
    "term": ["terim", "noun"],
    "total": ["toplam", "noun"],
    "unit": ["birim", "noun"],
    "value": ["değer", "noun"],
    "various": ["çeşitli", "adj"],
    "view": ["görüş", "noun"],
    "whether": ["-ip -mediğini", "conj"],
    "work": ["iş", "noun"],
    "year": ["yıl", "noun"],
    "ability": ["yetenek", "noun"],
    "achieve": ["başarmak", "verb"],
    "address": ["adres", "noun"],
    "analyze": ["analiz etmek", "verb"],
    "apply": ["uygulamak", "verb"],
    "attend": ["katılmak", "verb"],
    "benefit": ["yarar", "noun"],
    "beyond": ["ötesinde", "prep"],
    "campaign": ["kampanya", "noun"],
    "challenge": ["meydan okuma", "noun"],
    "commit": ["taahhüt etmek", "verb"],
    "communicate": ["iletişim kurmak", "verb"],
    "create": ["yaratmak", "verb"],
    "detail": ["detay", "noun"],
    "effect": ["etki", "noun"],
    "evaluate": ["değerlendirmek", "verb"],
    "finance": ["finans", "noun"],
    "focus": ["odak", "noun"],
    "identify": ["belirlemek", "verb"],
    "impact": ["etki", "noun"],
    "implement": ["uygulamak", "verb"],
    "improve": ["geliştirmek", "verb"],
    "increase": ["arttırmak", "verb"],
    "influence": ["etki", "noun"],
    "insight": ["görüş", "noun"],
    "invest": ["yatırım yapmak", "verb"],
    "manage": ["yönetmek", "verb"],
    "measure": ["ölçmek", "verb"],
    "modify": ["değiştirmek", "verb"],
    "negotiate": ["müzakere etmek", "verb"],
    "participate": ["katılmak", "verb"],
    "perform": ["performans göstermek", "verb"],
    "predict": ["tahmin etmek", "verb"],
    "promote": ["teşvik etmek", "verb"],
    "project": ["proje", "noun"],
    "review": ["incelemek", "verb"],
    "share": ["paylaşmak", "verb"],
    "succeed": ["başarmak", "verb"],
    "suggest": ["önermek", "verb"],
    "support": ["desteklemek", "verb"],
    "sustain": ["sürdürmek", "verb"],
    "target": ["hedef", "noun"],
    "validate": ["doğrulamak", "verb"],
    "verify": ["doğrulamak", "verb"],
}


def get_type_word(word):
    try:
        return english_turkish_dict[word][-1]
    except KeyError:
        return "Bu kelime yoktur lütfen modelin geçerli olan kelimelerinden verin"

    